name: Publish Docker Image

on:
  workflow_call:
    inputs:
      build-args:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: [self-hosted, docker-runner]
    steps:
      - name: Print
        run: env | sort

      - name: Cleanup the build folder
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set tag env
        run: |
          TAG=${GITHUB_REF#refs/*/}
          echo "DOCKERHUB_REPO=$GITHUB_REPOSITORY" >> $GITHUB_ENV
          
          if [[ $TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Release tag found"
            echo "TAGS=$GITHUB_REPOSITORY:latest,$GITHUB_REPOSITORY:$TAG" >> $GITHUB_ENV
          else
            echo "Feature tag found"
            echo "TAGS=$GITHUB_REPOSITORY:$TAG" >> $GITHUB_ENV          
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: ${{ env.DOCKERHUB_REPO }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.TAGS }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ inputs.build-args }}